### ISSUE TITLE
Total transacion count is incorrect

### ISSUE THREAD

**Issue by prostack364** [SphynxLabs/sphnyx-explorer#17]

**Comment by stackdev19** [comment]
It is related `CACHE_BLOCK_COUNT_PERIOD` has too large value. 7200s = 2hrs
I will set it into 3.

**Comment by prostack364** [comment]
We target to ensure response faster.
The basic SQL standard query to count the rows in a table can be rather slow because PostgreSQL has to check visibility for all rows, due to the [MVCC model](https://www.postgresql.org/docs/current/mvcc.html).
For more details, check for [here](https://wiki.postgresql.org/wiki/Count_estimate).

**Comment by prostack364** [comment]
We target to ensure response faster.
The basic SQL standard query to count the rows in a table can be rather slow because PostgreSQL has to check visibility for all rows, due to the [MVCC model](https://www.postgresql.org/docs/current/mvcc.html).
For more details, check for [here](https://wiki.postgresql.org/wiki/Count_estimate).
